### ISSUE TITLE
Integrate git

### ISSUE THREAD

**Issue by aiyan** [dracula/alacritty#2]
In the [Alacritty screenshot](https://github.com/dracula/alacritty/blob/master/screenshot.png), you can see the current git branch, commit status, and other UI tweaks.

Can someone send the (bashrc?) configuration so I can reproduce this screenshot? It might also be helpful to include the configuration in the `INSALL.md` file so other users can achieve the same results, as it is currently a bit misleading.

Many thanks!

**Comment by leandropincini** [comment]
Hi @aiyan how are you doing? I would like to thank you for your feedback!
There's a lot of installation needed to reproduce the screenshot.
We probably will change it to avoid further confusion.

BTW to get an alacritty equal to that you will need to install:

zsh
oh-my-zsh
dracula alacritty theme
dracula zsh theme

Good luck!

**Comment by aiyan** [comment]
Thanks for the steps, I was able to reproduce it!
